### PR TITLE
silence status of service in rlService{Start,Stop,Restore} functions

### LINKED ISSUE #41: confusing service status output in rlService*
if rlService* is called the current status is check first. This output is actually related to the previous service run so it is confusing if e.g. rlService Start is called but the status output says 'failed' even if the service start actually passed because the previous run failed.

If would be good to hide the initial service state check and eventually run service state check after the actual action so the relevant state is visible.

### PR DESCRIPTION
**Pull request by sopos**
The service status printed by `rlServiceStart` is actually the status of the
previous service run which is often misleading to the user.

I we want to print the status it should be relevant to the currently starting
service run, eg. status after the service is started.

As a compensation of this I introduced a new function `rlServiceStatus` to allow user to call it any time it is needed.

resolves #41

### CODE REVIEW

File: src/infrastructure.sh [hunk 1]
```diff
@@ -1292,6 +1292,44 @@ rlServiceRestore() {
     return $failed
 }
 
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+# rlServiceRestore
```
Comment (hegerj) [inline src/infrastructure.sh]: Copy/paste error

**Comment by sopos** [comment]
@hegerj, fixed the error.
What about the idea its self? Does it make sense to you? Isn't it too invasive? Someone might consider it as a regression..

**Comment by hegerj** [comment]
What exactly could be considered a regression? You are just adding new function right? Or is it connected to the redirection to /dev/null? I am not quite sure why are you adding those.

**Comment by sopos** [comment]
Yes, it is about the redirection. I muted the service status output to console of functions rlService{Start,Stop,Restore}.

**Comment by hegerj** [comment]
As long as exit codes stay the same I don't think it will be considered regression. After all man page guarantees only the exit code not the text output.

File: src/infrastructure.sh [hunk 2]
```diff
@@ -1292,6 +1292,44 @@ rlServiceRestore() {
...
+
+=over
+
+=item service
+
+Name of the service(s) to get the state.
+
+=back
+
+Returns status the last service.
```
Comment (AloisMahdal) [inline src/infrastructure.sh]: It's not clear now this maps to the integer value of exit status.

Also, grammar.. :)

File: src/infrastructure.sh [hunk 3]
```diff
@@ -1292,6 +1292,44 @@ rlServiceRestore() {
...
+
+=cut
+
+rlServiceStatus() {
+    local IFS
+    local res
+    res=0
+
```
Comment (AloisMahdal) [inline src/infrastructure.sh]: Just a nitpick: this newline seems extraneous...

File: src/infrastructure.sh [hunk 4]
```diff
@@ -1292,6 +1292,44 @@ rlServiceRestore() {
...
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+: <<'=cut'
+=pod
+
+=head3 rlServiceStatus
+
+Print status of given C<service>.
+
+    rlServiceStatus service [service...]
+
```
Comment (AloisMahdal) [inline src/infrastructure.sh]: It's not clear what is the main purpose of the function:  status collection (`case $(rlServiceStatus)`), status checking (`if rlServiceStatus..`) or just logging?

In the first case, it should be also clear what keywords it exactly prints. In the second case, it's unclear what are the exit statuses.  Eg. is both "running" and "enabled" reported, and how exactly?

File: src/infrastructure.sh (hunk 3 above)
Comment (sopos) [reply src/infrastructure.sh]: yes, it is not necessary, just a visual separator

File: src/infrastructure.sh (hunk 4 above)
Comment (sopos) [reply src/infrastructure.sh]: Good point! My original intention was just to print in to the console and return the same exit code as `service/systemctl` would (status checking). When more services are in question the result is not really ideal for machine processing. We might do something about that. Any suggestion?
I'm not sure if status collection is necessary to have but it might help to process situation with more then one service.

File: src/infrastructure.sh (hunk 2 above)
Comment (sopos) [reply src/infrastructure.sh]: This needs definitely to be fixed. The final fix will vary depending on the discussion above.

File: src/infrastructure.sh (hunk 4 above)
Comment (sopos) [reply src/infrastructure.sh]: I've done some tweaks, please check it.

**Comment by AloisMahdal** [comment]
Note that despite my bickering I'd still vote for silencing the statuses (I think I even proposed it years ago myself somewhere downstream) as is the main purpose of this PR.

The status printing has always been just non-essential side effect so IMO there's no neeed to make up for it, let alone in the same commit.

Why not just forget about `rlServiceStatus` at least for this PR; providing extra function here does not do anything for people who somehow rely on the verbosity anyway.  (I'd doubt there are very many..)  If BeakerLib should even have such function then I'd say it deserves more thought. (I've already learned myself the hard way that "service status" in systemd is not really a trivial 0/1 concept..)

**Comment by sopos** [comment]
Right, `rlServiceStatus` is something extra here. I just wanted to give a possibility to trigger it where needed. I've already implemented such function on various places for better test output readability. I think it might be useful to have it just for the reason it handles all the pager issues and different ways to call it natively.
The code was basically already there, I was just not exposed to the users.
So I take it as we reached an agreement. I will leave this first version there and it can evolve in the future if there are real users of it.

**Comment by sopos** [comment]
Why I'm not that confident about removing the status printing completely is that I often search for it in the output to guess what happened with the service while debugging some issue. After the removal there may be kind of regression of this debugging ability.
Currently it is quite tricky as I need to search for the later output to see the previous service state. That's also why I wanted to discuss it here first. I also considered to add another service status call after the service {start,stop,restore}. This way it would give me the up-to date output right after the service call. However, some services are not yet started after return from the service start call so printing the status that early could give irrelevant information.

**Comment by sopos** [comment]
Actually, I looked at the implementation and realized that, e.g. in `rlServiceStart` if the service start returns non-zero, the service status is printed. So the important part for debugging will stay there. Only non-fatal error will not be visible.

**Comment by AloisMahdal** [comment]
> So I take it as we reached an agreement. I will leave this first version there and it can evolve in the future if there are real users of it.

How do you know if there are "real users"? Once you introduce it, you *have* to assume people are using it.

Also, once you introduce an API, you should not change it.  Hence if unsure, don't introduce it.  Having crappy API in the library makes the library more crappy, especially if it's inconsistent.

> Why I'm not that confident about removing the status printing completely is that I often search for [...]

It's OK to remove non-essential undocumented side-effects, exactly because they are non-essential, undocumented side effects.  You can always find one person that uses it but with that argument you'd never be able to remove anything.

**Comment by sopos** [comment]
> How do you know if there are "real users"? Once you introduce it, you _have_ to assume people are using it.

I meant to let it evolve by RFEs and future bugs filed against it. If there are RFEs or bugs, there are "real users".
I'll be definitely one of them and it is enough for me to have it as it is proposed, of course.
